services:
  db:
    container_name: mysql-server
    image: mysql:latest
    ports:
      - ${{ secrets.DATABASE_PORT }}:3306
    volumes:
      - /home/${{ secrets.EC2_USERNAME }}/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secrets.DATABASE_ROOT_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.DATABASE_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 2s
      retries: 100

  backend:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge