services:
  db:
    container_name: mysql-server
    image: mysql:latest
    ports:
      - ${DATABASE_PORT}:3306  # 환경 변수로 변경
    volumes:
      - /home/${EC2_USERNAME}/data/mysql:/var/lib/mysql
      - /home/${EC2_USERNAME}/data/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 2s
      retries: 100

  backend:
    container_name: app
    image: ${DOCKERHUB_USERNAME}/app-with-actions:latest  # 환경 변수로 변경
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
